//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguridadTokenApiPeliculas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public Nullable<int> CPostal { get; set; }
        public string PaginaWeb { get; set; }
        public string Imagen_Cliente { get; set; }
    }
}
