//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguridadTokenApiPeliculas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextoPeliculas : DbContext
    {
        public ContextoPeliculas()
            : base("name=ContextoPeliculas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Distribuidoras> Distribuidoras { get; set; }
        public DbSet<Generos> Generos { get; set; }
        public DbSet<Nacionalidad> Nacionalidad { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<Peliculas> Peliculas { get; set; }
    }
}
