//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguridadTokenApiPeliculas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nacionalidad
    {
        public int IdNacionalidad { get; set; }
        public string Nacionalidad1 { get; set; }
        public string Bandera { get; set; }
    }
}
