//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguridadTokenApiPeliculas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int IdCliente { get; set; }
        public int IdPelicula { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Precio { get; set; }
    }
}
