//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguridadTokenApiPeliculas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int IdPelicula { get; set; }
        public Nullable<int> IdDistribuidor { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> IdNacionalidad { get; set; }
        public string Argumento { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> Fecha_Estreno { get; set; }
        public string Actores { get; set; }
        public string Director { get; set; }
        public Nullable<int> Duracion { get; set; }
        public Nullable<short> Precio { get; set; }
        public string YouTube { get; set; }
        public string EnlaceVideo { get; set; }
    }
}
